from typing import Any

from pyspark.sql.window import WindowSpec

class Column:
    def __init__(self, jc: Any = ...) -> None: ...
    def alias(self, *alias: str, **kwargs: Any) -> Column: ...
    def asc(self) -> Column: ...
    def asc_nulls_first(self) -> Column: ...
    def asc_nulls_last(self) -> Column: ...
    def desc(self) -> Column: ...
    def desc_nulls_first(self) -> Column: ...
    def desc_nulls_last(self) -> Column: ...
    def isNull(self) -> Column: ...
    def isNotNull(self) -> Column: ...
    def over(self, window: WindowSpec) -> Column: ...
    def cast(self, dataType: Any) -> Column: ...
    def otherwise(self, value: Any) -> Column: ...
    def when(self, condition: Column, value: Any) -> Column: ...
    def __eq__(self, other: object) -> Column: ...  # type: ignore[bad-override]
    def __ne__(self, other: object) -> Column: ...  # type: ignore[bad-override]
    def __lt__(self, other: object) -> Column: ...
    def __le__(self, other: object) -> Column: ...
    def __gt__(self, other: object) -> Column: ...
    def __ge__(self, other: object) -> Column: ...
    def __and__(self, other: object) -> Column: ...
    def __or__(self, other: object) -> Column: ...
    def __invert__(self) -> Column: ...
    def __add__(self, other: object) -> Column: ...
    def __sub__(self, other: object) -> Column: ...
    def __mul__(self, other: object) -> Column: ...
    def __truediv__(self, other: object) -> Column: ...
    def __mod__(self, other: object) -> Column: ...
